# Generated by Django 4.0 on 2021-12-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_first_name_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(max_length=64, unique=True, verbose_name='Адрес электронной почты'),
        ),
    ]
