# Generated by Django 4.0 on 2021-12-28 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_username'),
        ('main', '0005_alter_postreadhistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreadhistory',
            name='subscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.subscription'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postreadhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
    ]
