# Generated by Django 4.0 on 2021-12-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_postreadhistory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postreadhistory',
            name='subscription',
        ),
    ]
