# Generated by Django 4.0 on 2021-12-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_postreadhistory_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreadhistory',
            name='user',
            field=models.EmailField(max_length=254),
        ),
    ]
