# Generated by Django 4.0 on 2021-12-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_postreadhistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreadhistory',
            name='user',
            field=models.IntegerField(),
        ),
    ]
